### ISSUE TITLE
Add geofence to a particular region

### ISSUE THREAD

**Issue by fartbagxp** [fartbagxp/jump-host#9]
* https://www.axllent.org/docs/view/ssh-geoip/ has a great guide on how to do this.

**Comment by boris-ning-usds** [comment]
We cannot follow this guide, because [*aclexec* doesn't exists in Redhat](https://bugzilla.redhat.com/show_bug.cgi?id=1181815). It is supported in debian/ubuntu/fedora 22 though.

Alternatively, for Redhat, we should instead use this [guide for fail2ban](https://munkjensen.net/wiki/index.php/Access_control_using_Fail2Ban_and_geoip).

**Comment by boris-ning-usds** [comment]
We cannot follow this guide, because [*aclexec* doesn't exists in Redhat](https://bugzilla.redhat.com/show_bug.cgi?id=1181815). It is supported in debian/ubuntu/fedora 22 though.

Alternatively, for Redhat, we should instead use this [guide for fail2ban](https://munkjensen.net/wiki/index.php/Access_control_using_Fail2Ban_and_geoip).

**Comment by fartbagxp** [comment]
Added this ability!
